sudo: required
services: 
  - docker

before_install: 
  - docker build -t abyssmemes/docker-react -f Dockerfile.dev .  
  
script: 
  - docker run -e CI=true abyssmemes/docker-react npm run test 

language:  generic